# SITE CONFIGURATION
title: Keels
description: >
  A fork of Jekyll theme Sleek, developed through trial-and-error towards a
  compromise between speed and simplicity, and increased compatibility as
  remote theme for Github pages.
url: https://juseg.github.io

# THEME SETTINGS
tagline: A fork of Jekyll theme Sleek
navigation:
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}
email: your-email@domain.com  # email for form submission
github_username: juseg
# instagram_username:  # uncomment to add link in footer
# twitter_username:    # uncomment to add link in footer
# disqus:
#   shortname:  # uncomment to enable comments
# google_tag_manager: GTM-XXXXXXX  # uncomment to enable GTM.
# service_worker: true

# BUILD SETTINGS
# theme: jekyll-keels  # uncomment to use the theme as a ruby gem
# remote_theme: juseg/keels  # uncomment to use as a remote theme
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg
include:
  - _pages
permalink: /:title/
compress_html:
  clippings: all

# JEKYLL PLUGINS
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-sass-converter
